In [1]:
!pip3 install numpy

## ndarrays

In [2]:
import numpy as np
print(np.__version__)

1.24.3


In [3]:
lst=[5,67,87,45,23]
print(type(lst))
print(lst)

<class 'list'>
[5, 67, 87, 45, 23]


In [6]:
a=np.array(lst)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[ 5 67 87 45 23]


In [7]:
tup=(5,4,3,2)
a=np.array(tup)
print(a)
print(type(a))

[5 4 3 2]
<class 'numpy.ndarray'>


In [8]:
#2 dimensional array

a=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a)
print(a[1][1])
print(type(a))

[[4 5 6]
 [7 8 9]
 [1 2 3]]
8
<class 'numpy.ndarray'>


### np.zeros

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
np.linspace(0,10,num=3)

array([ 0.,  5., 10.])

### NUMPY sorting

In [3]:
arr = np.array([23,45,4,2,6,78,87])

# you can quickly sort the numbers in ascending order

np.sort(arr)

array([ 2,  4,  6, 23, 45, 78, 87])

### np.concatenate()

In [6]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,7,6,4])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 7, 6, 4])

In [9]:
x = np.array([[1,3],[4,5]])
y = np.array([[2,7]])

print(x)
print()
print(y)
print()
print(y.T)#T represent transpose
print()


print(np.concatenate((x,y),axis=0))
print()
print(np.concatenate((x,y.T),axis=1))


[[1 3]
 [4 5]]

[[2 7]]

[[2]
 [7]]

[[1 3]
 [4 5]
 [2 7]]

[[1 3 2]
 [4 5 7]]


### ndim()


In [3]:
array_example = np.array([[[0,1,2,3,4],
                          [4,5,6,7,8,]],
                          
                          [[0,1,2,3,4],
                          [4,5,6,7,8,]],
                          
                          [[0,1,2,3,4],
                          [4,5,6,7,8,]]])

In [18]:
print(array_example)

[[[0 1 2 3 4]
  [4 5 6 7 8]]

 [[0 1 2 3 4]
  [4 5 6 7 8]]

 [[0 1 2 3 4]
  [4 5 6 7 8]]]


In [19]:
array_example.ndim

3

In [20]:
array_example.size

30

### Reshape

In [24]:
import numpy as np
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [25]:
b=a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [31]:
a=np.arange(6)
b= a.reshape((3,2))
print(b)

[[0 1]
 [2 3]
 [4 5]]


### resize()

In [32]:
arr = np.array([1,2,3,4,5,6])
arr.resize((2,3))
print(arr)

[[1 2 3]
 [4 5 6]]


In [33]:
arr = np.array([1,2,3,4,5,6])
arr.resize((3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


### newaxis()

In [34]:
a=np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
print(a.ndim)

[1 2 3 4 5 6]
(6,)
1


In [35]:
a2=a[np.newaxis, :]
print(a2)
print(a2.shape)
print(a2.ndim)

[[1 2 3 4 5 6]]
(1, 6)
2


In [37]:
a3=a2[np.newaxis, :]
print(a3)
print(a3.shape)
print(a3.ndim)

[[[1 2 3 4 5 6]]]
(1, 1, 6)
3


In [38]:
row_vector = a[np.newaxis, :]
row_vector.shape
print(row_vector)

[[1 2 3 4 5 6]]


In [39]:
col_vector = a[: ,np.newaxis]
col_vector.shape
print(col_vector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### expand()

In [40]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [41]:
b = np.expand_dims(a,axis=1)
print(b.shape)
print(b.ndim)
print(b)

(6, 1)
2
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [44]:
c = np.expand_dims(a,axis=0)
print(c.shape)
print(c)

(1, 6)
[[1 2 3 4 5 6]]


### Indexing and Slicing

In [45]:
data = np.array([1,2,3,4,5,6,7,8])
data[1]

2

In [46]:
data[2:6]

array([3, 4, 5, 6])

In [47]:
data[-2:]

array([7, 8])

In [48]:
data[:3]

array([1, 2, 3])

In [50]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
print(a[a<5])

[1 2 3 4]


In [53]:
five_up = (a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [58]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [60]:
five_up = (a>5)|(a==5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


### Stacking of arrays

In [62]:
a1= np.array([[1,1],
            [2,2]])

a2= np.array([[3,3],
            [4,4]])

In [63]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [64]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

### split()

In [66]:
import numpy as np
x = np.arange(1,25).reshape(2,12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [68]:
# if you want four equally split array
print(np.hsplit(x,4))

[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4,  5,  6],
       [16, 17, 18]]), array([[ 7,  8,  9],
       [19, 20, 21]]), array([[10, 11, 12],
       [22, 23, 24]])]


In [72]:
#if you want to split at 3 and 5 coloumn
np.hsplit(x,(3,5))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

### Arithmetic operations

In [74]:
data = np.array([1,2])
ones = np.ones(2,dtype=int)
print(data)
print()
print(ones)
data+ones

[1 2]

[1 1]


array([2, 3])

In [76]:
print(data-ones)
print()
print(data*ones)
print()
print(data/ones)

[0 1]

[1 2]

[1. 2.]


In [5]:
import numpy as np
data = np.array([[1,2],[3,4],[5,6],[8,9]])

data

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 9]])

In [11]:
print(data[0,1])

print(data[1:4])

print(data[0:4,1])

2
[[3 4]
 [5 6]
 [8 9]]
[2 4 6 9]


### np.unique()

In [12]:
a = np.array([11,11,12,13,14,15,15,16,17,18,19,19,20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [13]:
unique_values ,indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  7  8  9 10 12]


In [14]:
a_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
unique_rows = np.unique(a_2d, axis = 0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
unique_columns = np.unique(a_2d, axis = 1)
print(unique_columns)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


### Transpose()

In [17]:
a= np.arange(6).reshape((2,3))
print(a)

[[0 1 2]
 [3 4 5]]


In [18]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [20]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### flip()

In [21]:
a= np.array([1,2,3,4,5,6,7,8])
reverse_array=np.flip(a)
print(reverse_array)

[8 7 6 5 4 3 2 1]


In [22]:
#2D
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
reverse_array = np.flip(a)
print(reverse_array)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [23]:
reverse_array_row = np.flip(a ,axis=0)
print(reverse_array_row)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [24]:
reverse_array_col = np.flip(a ,axis=1)
print(reverse_array_col)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
