In [ ]:
#1.Create a NumPy array a with values 1 through 9. Reshape the array to a 3x3 matrix.

In [2]:
import numpy as np

In [6]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#2.Create a NumPy array b with values 5 through 13. Reshape the array to a 3x3 matrix.

In [2]:
b=np.array([5,6,7,8,9,10,11,12,13])
b.reshape(3,3)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [ ]:
#3.Multiply the matrix a by the matrix b using the @ operator.

In [4]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])


print(a)
print(b)
result=a@b
print(result)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [ ]:
#4.Compute the dot product of the first row of a with the first column of b.

In [6]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

first_row_a = a[0]
first_column_b = b[:, 0]

dot_product = np.dot(first_row_a, first_column_b)

print("Dot product of the first row of a and the first column of b:", dot_product)

Dot product of the first row of a and the first column of b: 19


In [ ]:
#5.Compute the sum of all the elements in the matrix a.

In [7]:
a=np.array([[1,2],[3,4]])
np.sum(a)

10

In [ ]:
#6.Compute the product of all the elements in the matrix b.

In [18]:
b=np.array([[1,2,3],
          [4,5,6,],
            [7,8,9]])
product_b=np.product(b)
print(product_b)

362880


In [ ]:
#7.Create a 1D NumPy array c with values [1, 2, 3, 4, 5]. Use the np.insert() function to insert the value 0 at index 2.

In [24]:
c=np.array([1, 2, 3, 4, 5])

c=np.insert(c,2,0)
print(c)

[1 2 0 3 4 5]


In [ ]:
#8.Create a 1D NumPy array d with values [1, 2, 3, 4, 5]. Use the np.delete() function to delete the value at index 3.

In [27]:
d=np.array([1,2,3,4,5])

d=np.delete(d,3)

print(d)

[1 2 3 5]


In [ ]:
#9.Create a 2D NumPy array e with dimensions 3x4 and values 1 through 12. Use boolean indexing to select all elements
#greater than 5.

In [7]:
e = np.arange(1, 13).reshape(3, 4)


result = e[e > 5]

print(result)


[ 6  7  8  9 10 11 12]


In [ ]:
# 10.Create a 2D NumPy array f with dimensions 4x5 and values 1 through 20. Use fancy indexing to select the elements at
# positions (0,0), (1,2), and (2,4).

In [4]:
import numpy as np

f=np.arange(1, 21)

F=f.reshape(4,5)

selected_elements = F[[0, 1, 2], [0, 2, 4]]

print("Array F:")
print(F)

print("\nSelected elements at positions (0,0), (1,2), and (2,4):")
print(selected_elements)

Array F:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Selected elements at positions (0,0), (1,2), and (2,4):
[ 1  8 15]


In [ ]:
#11.Create a 2D NumPy array a with dimensions 5x5 and values 0.5 in the diagonal and 0 elsewhere.

In [10]:
import numpy as np

a = np.eye(5) * 0.5

print("Array a:")
print(a)

Array a:
[[0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.5]]


In [ ]:
#12.Create a 3D NumPy array b with dimensions 3x3x3 and random integer values between 0 and 10.

In [6]:
b = np.random.randint(0, 11, size=(3, 3, 3))

print("Array b:")
print(b)

Array b:
[[[ 0  2  3]
  [ 6  9  4]
  [ 8  9 10]]

 [[ 1  4 10]
  [ 7  5  1]
  [10  6  9]]

 [[ 6  5 10]
  [ 1  1  4]
  [ 3 10  4]]]


In [ ]:
#13.Compute the mean of each row of the matrix b.

In [7]:
row_mean=np.mean(b,axis=1)

print("mean of each row of matrix b:")
print(row_mean)

mean of each row of matrix b:
[[4.66666667 6.66666667 5.66666667]
 [6.         5.         6.66666667]
 [3.33333333 5.33333333 6.        ]]


In [ ]:
#14.Compute the standard deviation of each column of the matrix a.

In [13]:


mean_columns = np.mean(a, axis=0)

deviations = a - mean_columns

squared_deviations = deviations ** 2

mean_squared_deviations = np.mean(squared_deviations, axis=0)

standard_deviations = np.sqrt(mean_squared_deviations)

print('mean_columns:',mean_columns)
print("deviations:",deviations)
print("squared_deviations:",squared_deviations)
print("mean_squared_deviations :",mean_squared_deviations )
print("Standard Deviation of each column:", standard_deviations)

mean_columns: [0.1 0.1 0.1 0.1 0.1]
deviations: [[ 0.4 -0.1 -0.1 -0.1 -0.1]
 [-0.1  0.4 -0.1 -0.1 -0.1]
 [-0.1 -0.1  0.4 -0.1 -0.1]
 [-0.1 -0.1 -0.1  0.4 -0.1]
 [-0.1 -0.1 -0.1 -0.1  0.4]]
squared_deviations: [[0.16 0.01 0.01 0.01 0.01]
 [0.01 0.16 0.01 0.01 0.01]
 [0.01 0.01 0.16 0.01 0.01]
 [0.01 0.01 0.01 0.16 0.01]
 [0.01 0.01 0.01 0.01 0.16]]
mean_squared_deviations : [0.04 0.04 0.04 0.04 0.04]
Standard Deviation of each column: [0.2 0.2 0.2 0.2 0.2]


In [ ]:
#15.Compute the matrix multiplication of a with its transpose.

In [16]:
a_transpose=np.transpose(a)

multiply=np.dot(a,a_transpose)

print(multiply)

[[0.25 0.   0.   0.   0.  ]
 [0.   0.25 0.   0.   0.  ]
 [0.   0.   0.25 0.   0.  ]
 [0.   0.   0.   0.25 0.  ]
 [0.   0.   0.   0.   0.25]]


In [ ]:
# 16.Create a 2D NumPy array c with dimensions 6x6 and values 1 in the diagonal and 0 elsewhere. Use the np.roll()
# function to shift the values in each row to the right by one position.

In [17]:
c = np.eye(6)

c_shifted = np.roll(c, 1, axis=1)

print("Original array 'c':")
print(c)
print("\nShifted array 'c':")
print(c_shifted)

Original array 'c':
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Shifted array 'c':
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]


In [ ]:
# 17.Create a 2D NumPy array d with dimensions 4x4 and random values between 0 and 1. Normalize the values in each row to 
# have a sum of 1.

In [25]:
d = np.random.rand(4, 4)


row_sums = d.sum(axis=1) 
normalized_d = d / row_sums[:, np.newaxis]  

print("Original array 'd':")
print(d)
print("\nNormalized array 'd':")
print(normalized_d)

Original array 'd':
[[0.2920331  0.58736434 0.18387408 0.19033514]
 [0.22579079 0.21833601 0.34104623 0.68589093]
 [0.99437772 0.55315941 0.05208274 0.26431261]
 [0.87897151 0.39278099 0.40165625 0.19885217]]

Normalized array 'd':
[[0.23295433 0.46853958 0.14667605 0.15183003]
 [0.15348808 0.14842048 0.23183644 0.466255  ]
 [0.53348377 0.29677009 0.02794239 0.14180375]
 [0.46947063 0.20978966 0.21453006 0.10620965]]


In [24]:
# 18.Create a 2D NumPy array e with dimensions 3x3 and values 1 through 9. Use the np.flipud() function to flip the matrix
# vertically.

In [26]:
e = np.arange(1, 10).reshape(3, 3)

e_flipped = np.flipud(e)

print("Original array 'e':")
print(e)
print("\nVertically flipped array 'e':")
print(e_flipped)

Original array 'e':
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vertically flipped array 'e':
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
# 19.Create a 2D NumPy array f with dimensions 4x4 and random integer values between 0 and 10. Sort the values in each 
# row in ascending order.

In [27]:
f = np.random.randint(0, 11, size=(4, 4))

sorted_f = np.sort(f, axis=1)

print("Original array 'f':")
print(f)
print("\nSorted array 'f' in each row:")
print(sorted_f)

Original array 'f':
[[ 1  8  3  2]
 [ 4 10  8  2]
 [ 6  3  0  2]
 [ 3  9  0  6]]

Sorted array 'f' in each row:
[[ 1  2  3  8]
 [ 2  4  8 10]
 [ 0  2  3  6]
 [ 0  3  6  9]]


In [ ]:
# 20.Create a 2D NumPy array g with dimensions 5x5 and values 0 in the diagonal and 1 elsewhere. Use the np.linalg.inv() 
# function to compute the inverse of the matrix.

In [29]:
g = np.eye(5)

g = 1 - g

print("Array 'g' with 0 in diagonal and 1 elsewhere:")
print(g)

Array 'g' with 0 in diagonal and 1 elsewhere:
[[0. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]]
